Random card logo
WildCodeSchool/p2-g1-sept21-lille-react-magic pull request #13
Opened 2021-11-04 16:19 UTC by Caroline-CD

2021-11-04 16:21 UTC, John-athan14 submitted a review, later dismissed

2021-11-04 16:55 UTC, Hacene010 requested changes
Use camelCase everywhere plz to be coherent

2021-11-04 16:55 UTC, Hacene010 commented on src/Containers/CardDescription.css
> +.Container {
Use camelCase for all your calsseName to be coherent plz

2021-11-04 16:55 UTC, Hacene010 commented on src/Containers/CardDescription.css
> +.frame {
same here !!

2021-11-04 16:55 UTC, Hacene010 commented on src/Containers/CardDescription.css
> +.logo-reload {
Replace the kebab-case by camelCase too.

2021-11-04 16:55 UTC, Hacene010 commented on src/Containers/CardDescription.jsx
> +    <div className="Container">
Same problem with camelCase : /

2021-11-05 07:53 UTC, John-athan14 approved these changes

2021-11-05 10:58 UTC, Hacene010 approved these changes
that's better

2021-11-05 11:03 UTC, merged