Hotfix
WildCodeSchool/p2-g1-sept21-lille-react-magic pull request #15
Opened 2021-11-09 10:57 UTC by NacymeG

2021-11-09 10:59 UTC, John-athan14 submitted a review, later dismissed

2021-11-09 12:22 UTC, Hacene010 requested changes
Need to correct one thing

2021-11-09 12:22 UTC, Hacene010 commented on src/App.jsx
> +      style={{ backgroundImage: 'url(assets/img/backmg.jpg)' }}
no style here. You can put it into the app.css

2021-11-09 14:16 UTC, John-athan14 approved these changes, later dismissed

2021-11-10 07:53 UTC, John-athan14 approved these changes, later dismissed

2021-11-10 08:35 UTC, Hacene010 requested changes
Saw some evils please correct them.

2021-11-10 08:35 UTC, Hacene010 commented on src/Containers/CardDescription.jsx
> +              {' '}
- You can remove this

2021-11-10 08:35 UTC, Hacene010 commented on src/Containers/CardDescription.jsx
> +          {card.power ? (
You can do it with this syntax : {card.power && ....}

2021-11-10 08:35 UTC, Hacene010 commented on src/Containers/CardDescription.jsx
> +            🎨 &nbsp;&nbsp;{card.artist}&nbsp;&nbsp;&nbsp;-&nbsp;&nbsp;{' '}
- remove the {'  '} plz.

- code not very clean with these spaces

2021-11-10 08:35 UTC, Hacene010 commented on src/Containers/CardDescription.jsx
>            {card.flavor_text ? (
You can do it with this syntax : {card.flavor_text && ....}

2021-11-10 08:35 UTC, Hacene010 commented on src/Containers/CardDescription.jsx
> +            {card.name}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
I think you can do better than 5 spacements like that

2021-11-10 08:35 UTC, Hacene010 commented on src/Containers/CardDescription.jsx
> +          <p className="cardType">Set :&nbsp;{card.set_name}</p>
same here

2021-11-10 08:35 UTC, Hacene010 commented on src/Containers/CardDescription.jsx
> +          <p className="cardType">Rarity :&nbsp;{card.rarity}</p>
same here.

2021-11-10 10:11 UTC, Hacene010 approved these changes
Seems ok

2021-11-10 10:12 UTC, John-athan14 approved these changes

2021-11-10 10:12 UTC, merged