Cleaner
WildCodeSchool/p2-g1-sept21-lille-react-magic pull request #16
Opened 2021-11-10 15:40 UTC by NacymeG

2021-11-10 15:42 UTC, John-athan14 submitted a review, later dismissed

2021-11-15 09:05 UTC, Hacene010 requested changes
some changes to make

2021-11-15 09:05 UTC, Hacene010 commented on src/Components/MagicCard/MagicCard.jsx
> +      {imageUrl ? (
did this code (imageUrl &&...) not work ?

2021-11-15 09:05 UTC, Hacene010 commented on src/Components/SectionCaroussel/SectionCaroussel.jsx
> +  // const result = cardLists.filter((card) => card.imageUrl);
dead code here. 
Remove it plz

2021-11-15 11:25 UTC, Hacene010 approved these changes
seems ok

2021-11-15 18:16 UTC, John-athan14 approved these changes

2021-11-15 18:16 UTC, merged